# Change these first
owner: armadillu # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: uri.cat
    url: https://uri.cat
  - name: miniTerm Sant Feliu
    url: $SF_URL

assignees:
  - armadillu
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime Monitor for armadillu"
  introMessage: status
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  robotsText: "User-agent: * \n Disallow: /"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: armadillu
